import os

SESSION = "mysession"
CHAT_ID = "chat_id"
TOPIC_ID = "topic_id"
DUNE_API_KEY = "DUNE_API_KEY"
BIRDEYE_KEY = "BIRDEYE_KEY"
SOLANA_WS = "SOLANA_WS"
SOL_RPC = "SOL_RPC"
REDIS_URL = "REDIS_URL"
SOLANA_PRICE = "SOLANA_PRICE"
TRAIN_VAL_TEST_FILE = "train_val_test"
VALIDATION_FILE = "validation"
SUBSCRIPTION_MAP = "SUBSCRIPTION_MAP"
RANDOM_SEED = 42
INVESTMENT_AMOUNT = 50
DATABASE_NAME = "bigdatabot"
POSTGRES_USER = "POSTGRES_USER"
POSTGRES_PASSWORD = "POSTGRES_PASSWORD"

TRADE_QUEUE = "TRADE_QUEUE"
EVENT_QUEUE = "EVENT_QUEUE"
TOKEN_QUEUE = "TOKEN_QUEUE"
BIRD_EYE_COUNTER = "BIRD_EYE_COUNTER"

WIN_PERCENTAGE = 100
DRAW_DOWN_PERCENTAGE = 50

TRADE_LIST_QUERY = 4285100
TOP_TRADERS_QUERY = 4284967
TRADED_TOKENS_QUERY = 4285001
TOKEN_CLOSE_VOLUME_1M_QUERY = 4285111
CURRENT_CLOSE_VOLUME_1M_QUERY = 4285394
CURRENT_TRADE_LIST_QUERY = 4285376
TOKEN_CREATE_TIME_QUERY = 4342831
PRODUCTION_TEST_TRADES = 4436495
PRODUCTION_TEST_PRICE = 4436554

PRICE_COLUMN = "latest_price"
PRICE_PCT_CHANGE = "price_pct_change"
TOTAL_VOLUME_PCT_CHANGE = "total_volume_pct_change"
SELL_VOLUME_PCT_CHANGE = "sell_volume_pct_change"
BUY_VOLUME_PCT_CHANGE = "buy_volume_pct_change"
TOKEN_COlUMN = "token"
TRADING_MINUTE_COLUMN = "trading_minute"
LABEL_COLUMN = "label"
BUY_VOLUME_COLUMN = 'buy_volume'
SELL_VOLUME_COLUMN = 'sell_volume'
TOTAL_VOLUME_COLUMN = 'total_volume'
SOL_PRICE = 170
MARKET_CAP_USD = 'market_cap_usd'
PERCENTAGE_OF_1_MILLION_MARKET_CAP = 'percentage_of_1_million_market_cap'

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
CACHE_FOLDER = os.path.join(ROOT_DIR, "cache")
MODEL_FOLDER = os.path.join(ROOT_DIR, "save_models")
CONFIG_2_FILE = os.path.join(ROOT_DIR, "pipeline", "config", "2_prepare_data_sets.yaml")

BIN_AMOUNT_KEY = "bin_amount"
PUMP_DOT_FUN_ID = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
RAYDIUM_ID = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"
PUMP_DOT_FUN_AUTHORITY = "TSLvdd1pWpHVjahSpsvCXUbgwsL3JAcvokwaKt1eokM"
TOKEN_WATCHER_KEY = "TOKEN_WATCHER_KEY"
