services:
  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: always

  grafana:
    image: grafana/grafana:10.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - loki
    restart: always

  # Redis service for queue management
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app_network
    command: [ "redis-server", "--appendonly", "yes" ] # Enables AOF for persistence
    restart: always

volumes:
  loki_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge