services:

  token_sampler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python pipeline/token_sampler.py
    volumes:
      - ./cache:/app/cache           # Map host ./cache to /app/cache in the container
    networks:
      - app_network

networks:
  app_network:
    driver: bridge